In [54]:
#lab2_1
import numpy as np
from numpy import linalg
A =  np.array([[1,-2,3,5],[2,2,-1,0],[3,0,1,2,],[1,0,2,0]])
print("행렬 A:\n",A)

print("\nA*2:\n",2*A)

print("\n행렬 A의 전치행렬:\n",A.T)

#print("\n행렬 A의 역행렬:\n",np.linalg.inv(A))
print("\n행렬 A의 역행렬:\n",linalg.inv(A))

행렬 A:
 [[ 1 -2  3  5]
 [ 2  2 -1  0]
 [ 3  0  1  2]
 [ 1  0  2  0]]

A*2:
 [[ 2 -4  6 10]
 [ 4  4 -2  0]
 [ 6  0  2  4]
 [ 2  0  4  0]]

행렬 A의 전치행렬:
 [[ 1  2  3  1]
 [-2  2  0  0]
 [ 3 -1  1  2]
 [ 5  0  2  0]]

행렬 A의 역행렬:
 [[-0.23529412 -0.23529412  0.58823529 -0.05882353]
 [ 0.29411765  0.79411765 -0.73529412  0.32352941]
 [ 0.11764706  0.11764706 -0.29411765  0.52941176]
 [ 0.29411765  0.29411765 -0.23529412 -0.17647059]]


In [60]:
#lab2_5
import numpy as np
from math import *

B = ([3,-4,-1.2,0,2.3])

def myNorm(Matrix,p):
    temp_Matrix = np.abs(Matrix)
    if p == 1:
        return np.sum(temp_Matrix)
    for i in range(p-1):
        temp_Matrix = np.multiply(temp_Matrix,np.abs(Matrix))
    return np.sum(temp_Matrix)**(1.0/p)

print("행렬 B의 1차 norm: ",myNorm(B,1),"\n")
print("행렬 B의 2차 norm: ",myNorm(B,2),"\n")
print("행렬 B의 3차 norm: ",myNorm(B,3),"\n")
print("행렬 B의 최대 norm: ",max(myNorm(B,1),myNorm(B,2),myNorm(B,3)),"\n")

행렬 B의 1차 norm:  10.5 

행렬 B의 2차 norm:  5.632938842203065 

행렬 B의 3차 norm:  4.716120891176797 

행렬 B의 최대 norm:  10.5 



In [65]:
#lab2_12
def f(x):
    return 2*(1.0/4(1-2*x)**2-1)**3-3(1.0/4(1-2*x)**2-1)**2-3