In [120]:
#lab2_1
import numpy as np
from numpy import linalg
A =  np.array([[1,-2,3,5],[2,2,-1,0],[3,0,1,2,],[1,0,2,0]])
print("행렬 A:\n",A)

print("\nA*2:\n",2*A)

print("\n행렬 A의 전치행렬:\n",A.T)

#print("\n행렬 A의 역행렬:\n",np.linalg.inv(A))
print("\n행렬 A의 역행렬:\n",linalg.inv(A))

행렬 A:
 [[ 1 -2  3  5]
 [ 2  2 -1  0]
 [ 3  0  1  2]
 [ 1  0  2  0]]

A*2:
 [[ 2 -4  6 10]
 [ 4  4 -2  0]
 [ 6  0  2  4]
 [ 2  0  4  0]]

행렬 A의 전치행렬:
 [[ 1  2  3  1]
 [-2  2  0  0]
 [ 3 -1  1  2]
 [ 5  0  2  0]]

행렬 A의 역행렬:
 [[-0.23529412 -0.23529412  0.58823529 -0.05882353]
 [ 0.29411765  0.79411765 -0.73529412  0.32352941]
 [ 0.11764706  0.11764706 -0.29411765  0.52941176]
 [ 0.29411765  0.29411765 -0.23529412 -0.17647059]]


In [122]:
#lab2_5_1
import numpy as np
from math import *

C = np.array([3,-4,-1.2,0,2.3])

B = C.T

def myNorm(Matrix,p):
    temp_Matrix = np.abs(Matrix)
    if p == 1:
        return np.sum(temp_Matrix)
    for i in range(p-1):
        temp_Matrix = np.multiply(temp_Matrix,np.abs(Matrix))
    return np.sum(temp_Matrix)**(1.0/p)

print("행렬 B의 1차 norm: ",myNorm(B,1),"\n")
print("행렬 B의 2차 norm: ",myNorm(B,2),"\n")
print("행렬 B의 3차 norm: ",myNorm(B,3),"\n")
print("행렬 B의 최대 norm: ",max(abs(B)),"\n")

행렬 B의 1차 norm:  10.5 

행렬 B의 2차 norm:  5.632938842203065 

행렬 B의 3차 norm:  4.716120891176797 

행렬 B의 최대 norm:  4.0 



In [126]:
#lab2_5_2
import numpy as np

D = np.array([[2,1],[1,5],[4,1]])

def Frobenius(a):
    result = 0;
    for row_list in a:
        for i in range(len(row_list)):
            result = result + (row_list[i]**2)       
    return result**(1.0/2)

print("D의 프로베니우스 놈:\n",Frobenius(D))

D의 프로베니우스 놈:
 6.928203230275509


In [138]:
#lab2_12
import sympy as sp

x = sp.symbols('x')
g, h, i = sp.symbols('g h i',cls=sp.Function)

i = 1-2*x
h = 1.0/4*(1-2*x)**2 - 1
g = 2*(1.0/4*(1-2*x)**2 - 1)**3-3*(1.0/4*(1-2*x)**2 - 1)**2-3
print("(1)")
print("f(x) = g(x) = ",g,"\n")

g1 = g.replace("1.0/4*(1-2*x)**2 - 1","h(x)")
g1_ = sp.factor(sp.diff(g1,x))
print("f(x) = g(h(x)) = ",g1,)
print("f\'(x) = g\'(h(x))*h\'(x) =",g1_)
print("h(x) = ",h)
print ("h\'(x) = ",sp.diff(h,x),"\n")

g2 = g.replace("1-2*x","i(x)")
g2_ = sp.factor(sp.diff(g2,x))
print("f(x) = g(h(i(x))) = ",g2)
print("f\'(x) = g\'(h(i(x)))*h\'(i(x))*i\'(x) =",g2_)
print("i(x) =",i)
print("i\'(x) =",sp.diff(i,x),"\n")

print("(2)\nf\'(x) =",sp.diff(g,x),"\n")
print("(3)")
print("f\'(0) =",sp.diff(g).subs({x:0}))
print("f\'(2.1) =",sp.diff(g).subs({x:2.1}))

(1)
f(x) = g(x) =  2*(0.25*(-2*x + 1)**2 - 1)**3 - 3*(0.25*(-2*x + 1)**2 - 1)**2 - 3 

f(x) = g(h(x)) =  2*h(x)**3 - 3*h(x)**2 - 3
f'(x) = g'(h(x))*h'(x) = 6*(h(x) - 1)*h(x)*Derivative(h(x), x)
h(x) =  0.25*(-2*x + 1)**2 - 1
h'(x) =  2.0*x - 1.0 

f(x) = g(h(i(x))) =  2*(0.25*i(x)**2 - 1)**3 - 3*(0.25*i(x)**2 - 1)**2 - 3
f'(x) = g'(h(i(x)))*h'(i(x))*i'(x) = 6.0*(0.5*i(x) - 1.0)*(0.5*i(x) + 1.0)*(0.125*i(x)**2 - 1.0)*i(x)*Derivative(i(x), x)
i(x) = -2*x + 1
i'(x) = -2 

(2)
f'(x) = -3*(4.0*x - 2.0)*(0.25*(-2*x + 1)**2 - 1) + 2*(6.0*x - 3.0)*(0.25*(-2*x + 1)**2 - 1)**2 

(3)
f'(0) = -7.87500000000000
f'(2.1) = 16.7731200000000
